services:
  - type: web
    name: inventory-system
    env: php
    plan: free
    buildCommand: ""
    startCommand: php -S 0.0.0.0:$PORT -t .
    envVars:
      - key: APP_URL
        value: https://inventory-system-cigq.onrender.com
      - key: SMTP_HOST
        value: localhost
      - key: SMTP_PORT
        value: 25
      - key: SMTP_FROM_ADDR
        value: noreply@inventory-system.local
      - key: SMTP_FROM_NAME
        value: Inventory System
      - key: SMTP_USERNAME
        value: ""
      - key: SMTP_PASSWORD
        value: ""
